# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CartonLableUI.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGroupBox, QHeaderView, QLCDNumber, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(895, 992)
        Dialog.setMinimumSize(QSize(878, 0))
        icon = QIcon()
        icon.addFile(u"C:/Users/user/Pictures/carton.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 70, 841, 81))
        font = QFont()
        font.setFamilies([u"Arial"])
        self.groupBox.setFont(font)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 24, 91, 31))
        font1 = QFont()
        font1.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font1.setPointSize(23)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.edit_InputMac = QLineEdit(self.groupBox)
        self.edit_InputMac.setObjectName(u"edit_InputMac")
        self.edit_InputMac.setGeometry(QRect(120, 20, 261, 41))
        self.edit_InputMac.setCursor(QCursor(Qt.CursorShape.CrossCursor))
        self.edit_InputMac.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_InputSN = QLineEdit(self.groupBox)
        self.edit_InputSN.setObjectName(u"edit_InputSN")
        self.edit_InputSN.setGeometry(QRect(560, 24, 261, 41))
        self.edit_InputSN.setCursor(QCursor(Qt.CursorShape.CrossCursor))
        self.edit_InputSN.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(470, 26, 91, 31))
        self.label_3.setFont(font1)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 26, 91, 21))
        font2 = QFont()
        font2.setFamilies([u"Arial Black"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.label.setFont(font2)
        self.combo_ModelList = QComboBox(Dialog)
        self.combo_ModelList.addItem("")
        self.combo_ModelList.setObjectName(u"combo_ModelList")
        self.combo_ModelList.setGeometry(QRect(122, 24, 201, 31))
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 160, 841, 81))
        self.groupBox_2.setFont(font)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(90, 30, 101, 31))
        font3 = QFont()
        font3.setFamilies([u"\ud5e4\ub4dc\ub77c\uc778"])
        font3.setPointSize(20)
        font3.setBold(False)
        font3.setUnderline(True)
        self.label_4.setFont(font3)
        self.lcd_TodayProduct = QLCDNumber(self.groupBox_2)
        self.lcd_TodayProduct.setObjectName(u"lcd_TodayProduct")
        self.lcd_TodayProduct.setGeometry(QRect(400, 30, 101, 31))
        self.lcd_TodayBox = QLCDNumber(self.groupBox_2)
        self.lcd_TodayBox.setObjectName(u"lcd_TodayBox")
        self.lcd_TodayBox.setGeometry(QRect(690, 30, 101, 31))
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(260, 30, 131, 31))
        font4 = QFont()
        font4.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font4.setPointSize(15)
        font4.setBold(True)
        self.label_6.setFont(font4)
        self.label_6.setStyleSheet(u"background-color:rgb(238, 255, 222);\n"
"color:black;")
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(550, 30, 131, 31))
        self.label_7.setFont(font4)
        self.label_7.setStyleSheet(u"background-color:rgb(238, 255, 222);\n"
"color:black;")
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_PrdSearch = QPushButton(Dialog)
        self.btn_PrdSearch.setObjectName(u"btn_PrdSearch")
        self.btn_PrdSearch.setGeometry(QRect(490, 430, 111, 41))
        font5 = QFont()
        font5.setBold(True)
        self.btn_PrdSearch.setFont(font5)
        self.btn_PrdSearch.setAutoDefault(False)
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(620, 430, 111, 41))
        font6 = QFont()
        font6.setPointSize(10)
        font6.setBold(True)
        self.pushButton_2.setFont(font6)
        self.pushButton_2.setAutoDefault(False)
        self.btn_PrintNow = QPushButton(Dialog)
        self.btn_PrintNow.setObjectName(u"btn_PrintNow")
        self.btn_PrintNow.setGeometry(QRect(750, 430, 111, 41))
        self.btn_PrintNow.setFont(font6)
        self.btn_PrintNow.setAutoDefault(False)
        self.tableWidget = QTableWidget(Dialog)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(30, 480, 831, 491))
        self.tableWidget.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(True)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 250, 841, 81))
        self.groupBox_3.setFont(font)
        self.lineEdit_7 = QLineEdit(self.groupBox_3)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(10, 30, 131, 31))
        font7 = QFont()
        font7.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font7.setPointSize(13)
        font7.setBold(True)
        self.lineEdit_7.setFont(font7)
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_7.setReadOnly(True)
        self.lcd_PrdBoxCnt = QLCDNumber(self.groupBox_3)
        self.lcd_PrdBoxCnt.setObjectName(u"lcd_PrdBoxCnt")
        self.lcd_PrdBoxCnt.setGeometry(QRect(150, 30, 101, 31))
        self.lineEdit_8 = QLineEdit(self.groupBox_3)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(290, 30, 131, 31))
        self.lineEdit_8.setFont(font7)
        self.lineEdit_8.setFrame(False)
        self.lineEdit_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_8.setReadOnly(True)
        self.lcd_TrayBoxCnt = QLCDNumber(self.groupBox_3)
        self.lcd_TrayBoxCnt.setObjectName(u"lcd_TrayBoxCnt")
        self.lcd_TrayBoxCnt.setGeometry(QRect(430, 30, 101, 31))
        self.lineEdit_9 = QLineEdit(self.groupBox_3)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(580, 30, 131, 31))
        self.lineEdit_9.setFont(font7)
        self.lineEdit_9.setFrame(False)
        self.lineEdit_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_9.setReadOnly(True)
        self.lcd_RemainTray = QLCDNumber(self.groupBox_3)
        self.lcd_RemainTray.setObjectName(u"lcd_RemainTray")
        self.lcd_RemainTray.setGeometry(QRect(720, 30, 101, 31))
        self.edit_ChoicedModel = QLineEdit(Dialog)
        self.edit_ChoicedModel.setObjectName(u"edit_ChoicedModel")
        self.edit_ChoicedModel.setGeometry(QRect(330, 15, 351, 51))
        font8 = QFont()
        font8.setFamilies([u"Arial"])
        font8.setPointSize(24)
        font8.setBold(True)
        self.edit_ChoicedModel.setFont(font8)
        self.edit_ChoicedModel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 449, 56, 12))
        font9 = QFont()
        font9.setPointSize(11)
        font9.setBold(True)
        self.label_10.setFont(font9)
        self.edit_Grid_Cnt = QLineEdit(Dialog)
        self.edit_Grid_Cnt.setObjectName(u"edit_Grid_Cnt")
        self.edit_Grid_Cnt.setEnabled(True)
        self.edit_Grid_Cnt.setGeometry(QRect(102, 440, 61, 31))
        font10 = QFont()
        font10.setPointSize(12)
        font10.setBold(True)
        self.edit_Grid_Cnt.setFont(font10)
        self.edit_Grid_Cnt.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_Grid_Cnt.setReadOnly(True)
        self.groupBox_4 = QGroupBox(Dialog)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 340, 651, 71))
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(14, 30, 121, 21))
        self.label_5.setFont(font2)
        self.edit_FW = QLineEdit(self.groupBox_4)
        self.edit_FW.setObjectName(u"edit_FW")
        self.edit_FW.setGeometry(QRect(140, 20, 111, 41))
        self.edit_FW.setMaxLength(5)
        self.edit_FW.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(290, 30, 91, 21))
        self.label_8.setFont(font2)
        self.edit_PanID = QLineEdit(self.groupBox_4)
        self.edit_PanID.setObjectName(u"edit_PanID")
        self.edit_PanID.setGeometry(QRect(380, 20, 111, 41))
        self.edit_PanID.setMaxLength(8)
        self.edit_PanID.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_BaseInfoSave = QPushButton(self.groupBox_4)
        self.btn_BaseInfoSave.setObjectName(u"btn_BaseInfoSave")
        self.btn_BaseInfoSave.setGeometry(QRect(520, 20, 111, 41))
        font11 = QFont()
        font11.setPointSize(15)
        font11.setBold(True)
        font11.setUnderline(True)
        self.btn_BaseInfoSave.setFont(font11)
        self.btn_BaseInfoSave.setAutoDefault(False)
        self.btn_DataClear = QPushButton(Dialog)
        self.btn_DataClear.setObjectName(u"btn_DataClear")
        self.btn_DataClear.setGeometry(QRect(360, 430, 111, 41))
        self.btn_DataClear.setFont(font5)
        self.btn_DataClear.setAutoDefault(False)
        self.btn_Test = QPushButton(Dialog)
        self.btn_Test.setObjectName(u"btn_Test")
        self.btn_Test.setEnabled(True)
        self.btn_Test.setGeometry(QRect(260, 430, 71, 41))
        self.btn_Test.setFont(font5)
        self.btn_Test.setAutoDefault(False)
        self.check_Conveyor = QCheckBox(Dialog)
        self.check_Conveyor.setObjectName(u"check_Conveyor")
        self.check_Conveyor.setGeometry(QRect(690, 19, 96, 19))
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(690, 49, 81, 16))
        self.edit_Comport = QLineEdit(Dialog)
        self.edit_Comport.setObjectName(u"edit_Comport")
        self.edit_Comport.setGeometry(QRect(770, 43, 91, 31))
        self.edit_Comport.setReadOnly(True)
        self.groupBox_5 = QGroupBox(Dialog)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(700, 350, 161, 61))
        self.check_Rma = QCheckBox(self.groupBox_5)
        self.check_Rma.setObjectName(u"check_Rma")
        self.check_Rma.setGeometry(QRect(20, 10, 131, 41))
        font12 = QFont()
        font12.setPointSize(13)
        font12.setBold(True)
        self.check_Rma.setFont(font12)
        QWidget.setTabOrder(self.edit_InputMac, self.edit_InputSN)
        QWidget.setTabOrder(self.edit_InputSN, self.btn_DataClear)
        QWidget.setTabOrder(self.btn_DataClear, self.btn_PrdSearch)
        QWidget.setTabOrder(self.btn_PrdSearch, self.pushButton_2)
        QWidget.setTabOrder(self.pushButton_2, self.btn_PrintNow)
        QWidget.setTabOrder(self.btn_PrintNow, self.edit_Grid_Cnt)
        QWidget.setTabOrder(self.edit_Grid_Cnt, self.tableWidget)
        QWidget.setTabOrder(self.tableWidget, self.combo_ModelList)
        QWidget.setTabOrder(self.combo_ModelList, self.edit_ChoicedModel)
        QWidget.setTabOrder(self.edit_ChoicedModel, self.lineEdit_7)
        QWidget.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        QWidget.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        QWidget.setTabOrder(self.lineEdit_9, self.edit_FW)
        QWidget.setTabOrder(self.edit_FW, self.edit_PanID)
        QWidget.setTabOrder(self.edit_PanID, self.btn_BaseInfoSave)

        self.retranslateUi(Dialog)
        self.combo_ModelList.currentIndexChanged.connect(Dialog.comboModelChanged)
        self.edit_InputMac.returnPressed.connect(Dialog.InputMacCheck)
        self.edit_InputSN.returnPressed.connect(Dialog.InputSnCheck)
        self.btn_PrdSearch.clicked.connect(Dialog.btnPrdSearchClicked)
        self.btn_BaseInfoSave.clicked.connect(Dialog.btnBaseInfoSaveClicked)
        self.btn_PrintNow.clicked.connect(Dialog.btnPrintNowClicked)
        self.pushButton_2.clicked.connect(Dialog.btnRePrintClicked)
        self.btn_DataClear.clicked.connect(Dialog.btnDataClearCllicked)
        self.btn_Test.clicked.connect(Dialog.btnTestClicked)
        self.check_Conveyor.stateChanged.connect(Dialog.setCheckComportChanged)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Compare", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"MAC :", None))
        self.edit_InputMac.setPlaceholderText(QCoreApplication.translate("Dialog", u"Input MacAddress", None))
        self.edit_InputSN.setPlaceholderText(QCoreApplication.translate("Dialog", u"Input Serial Number", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"S/N :", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"MODEL  ::", None))
        self.combo_ModelList.setItemText(0, QCoreApplication.translate("Dialog", u"Select Model", None))

        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Quantity", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"TODAY", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"PRODUCT", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"BOX", None))
        self.btn_PrdSearch.setText(QCoreApplication.translate("Dialog", u"MAC/SN Search", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Re-Print", None))
        self.btn_PrintNow.setText(QCoreApplication.translate("Dialog", u"Print Now", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Box/Tray Count Info", None))
        self.lineEdit_7.setText(QCoreApplication.translate("Dialog", u"BOX Count", None))
        self.lineEdit_8.setText(QCoreApplication.translate("Dialog", u"TRAY Count", None))
        self.lineEdit_9.setText(QCoreApplication.translate("Dialog", u"Remain TRAY", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Count :: ", None))
        self.edit_Grid_Cnt.setInputMask("")
        self.edit_Grid_Cnt.setPlaceholderText(QCoreApplication.translate("Dialog", u"0", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Base Info", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"F/W Version ::", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"PAN ID ::", None))
        self.btn_BaseInfoSave.setText(QCoreApplication.translate("Dialog", u"Save", None))
        self.btn_DataClear.setText(QCoreApplication.translate("Dialog", u"Data Clear", None))
        self.btn_Test.setText(QCoreApplication.translate("Dialog", u"Test", None))
        self.check_Conveyor.setText(QCoreApplication.translate("Dialog", u"Conveyor", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"COMPORT ::", None))
        self.groupBox_5.setTitle("")
        self.check_Rma.setText(QCoreApplication.translate("Dialog", u"RMA CHECK ", None))
    # retranslateUi

