# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PalletAddrUI.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QGroupBox,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTextEdit, QWidget)

class Ui_dlgPalletAddr(object):
    def setupUi(self, dlgPalletAddr):
        if not dlgPalletAddr.objectName():
            dlgPalletAddr.setObjectName(u"dlgPalletAddr")
        dlgPalletAddr.resize(966, 612)
        self.groupBox = QGroupBox(dlgPalletAddr)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 100, 431, 371))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(18, 32, 101, 21))
        font = QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.edit_FromAddr1 = QLineEdit(self.groupBox)
        self.edit_FromAddr1.setObjectName(u"edit_FromAddr1")
        self.edit_FromAddr1.setGeometry(QRect(17, 60, 391, 41))
        self.edit_FromAddr2 = QLineEdit(self.groupBox)
        self.edit_FromAddr2.setObjectName(u"edit_FromAddr2")
        self.edit_FromAddr2.setGeometry(QRect(19, 158, 391, 41))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 130, 101, 21))
        self.label_2.setFont(font)
        self.edit_FromAddr3 = QLineEdit(self.groupBox)
        self.edit_FromAddr3.setObjectName(u"edit_FromAddr3")
        self.edit_FromAddr3.setGeometry(QRect(19, 258, 391, 41))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 230, 101, 21))
        self.label_3.setFont(font)
        self.btn_FromPreview = QPushButton(self.groupBox)
        self.btn_FromPreview.setObjectName(u"btn_FromPreview")
        self.btn_FromPreview.setGeometry(QRect(70, 320, 121, 41))
        self.btn_FromPreview.setFont(font)
        self.btn_FromPreview.setAutoDefault(False)
        self.btn_FromSave = QPushButton(self.groupBox)
        self.btn_FromSave.setObjectName(u"btn_FromSave")
        self.btn_FromSave.setGeometry(QRect(240, 320, 121, 41))
        self.btn_FromSave.setFont(font)
        self.btn_FromSave.setAutoDefault(False)
        self.groupBox_2 = QGroupBox(dlgPalletAddr)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(500, 100, 431, 371))
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(21, 32, 101, 21))
        self.label_6.setFont(font)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(23, 230, 101, 21))
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(23, 130, 101, 21))
        self.label_5.setFont(font)
        self.edit_ToAddr2 = QLineEdit(self.groupBox_2)
        self.edit_ToAddr2.setObjectName(u"edit_ToAddr2")
        self.edit_ToAddr2.setGeometry(QRect(22, 158, 391, 41))
        self.btn_ToSave = QPushButton(self.groupBox_2)
        self.btn_ToSave.setObjectName(u"btn_ToSave")
        self.btn_ToSave.setGeometry(QRect(243, 320, 121, 41))
        self.btn_ToSave.setFont(font)
        self.btn_ToSave.setAutoDefault(False)
        self.btn_ToPreview = QPushButton(self.groupBox_2)
        self.btn_ToPreview.setObjectName(u"btn_ToPreview")
        self.btn_ToPreview.setGeometry(QRect(73, 320, 121, 41))
        self.btn_ToPreview.setFont(font)
        self.btn_ToPreview.setAutoDefault(False)
        self.edit_ToAddr3 = QLineEdit(self.groupBox_2)
        self.edit_ToAddr3.setObjectName(u"edit_ToAddr3")
        self.edit_ToAddr3.setGeometry(QRect(22, 258, 391, 41))
        self.edit_ToAddr1 = QLineEdit(self.groupBox_2)
        self.edit_ToAddr1.setObjectName(u"edit_ToAddr1")
        self.edit_ToAddr1.setGeometry(QRect(20, 60, 391, 41))
        self.edit_FromPreview = QTextEdit(dlgPalletAddr)
        self.edit_FromPreview.setObjectName(u"edit_FromPreview")
        self.edit_FromPreview.setGeometry(QRect(20, 490, 431, 111))
        self.edit_FromPreview.setReadOnly(True)
        self.edit_ToPreview = QTextEdit(dlgPalletAddr)
        self.edit_ToPreview.setObjectName(u"edit_ToPreview")
        self.edit_ToPreview.setGeometry(QRect(500, 490, 431, 111))
        self.edit_ToPreview.setReadOnly(True)
        self.combo_ModelList = QComboBox(dlgPalletAddr)
        self.combo_ModelList.addItem("")
        self.combo_ModelList.setObjectName(u"combo_ModelList")
        self.combo_ModelList.setGeometry(QRect(122, 38, 271, 31))
        self.label_7 = QLabel(dlgPalletAddr)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 40, 91, 21))
        font1 = QFont()
        font1.setFamilies([u"Arial Black"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_7.setFont(font1)
        QWidget.setTabOrder(self.edit_FromAddr1, self.edit_FromAddr2)
        QWidget.setTabOrder(self.edit_FromAddr2, self.edit_FromAddr3)
        QWidget.setTabOrder(self.edit_FromAddr3, self.btn_FromPreview)
        QWidget.setTabOrder(self.btn_FromPreview, self.btn_FromSave)
        QWidget.setTabOrder(self.btn_FromSave, self.edit_ToAddr1)
        QWidget.setTabOrder(self.edit_ToAddr1, self.edit_ToAddr2)
        QWidget.setTabOrder(self.edit_ToAddr2, self.edit_ToAddr3)
        QWidget.setTabOrder(self.edit_ToAddr3, self.btn_ToPreview)
        QWidget.setTabOrder(self.btn_ToPreview, self.btn_ToSave)
        QWidget.setTabOrder(self.btn_ToSave, self.edit_ToPreview)
        QWidget.setTabOrder(self.edit_ToPreview, self.edit_FromPreview)

        self.retranslateUi(dlgPalletAddr)
        self.btn_FromPreview.pressed.connect(dlgPalletAddr.btnFromPreview)
        self.btn_FromSave.clicked.connect(dlgPalletAddr.btnFromSave)
        self.btn_ToPreview.clicked.connect(dlgPalletAddr.btnToPreview)
        self.btn_ToSave.clicked.connect(dlgPalletAddr.btnToSave)
        self.combo_ModelList.currentIndexChanged.connect(dlgPalletAddr.comboModelChanged)

        QMetaObject.connectSlotsByName(dlgPalletAddr)
    # setupUi

    def retranslateUi(self, dlgPalletAddr):
        dlgPalletAddr.setWindowTitle(QCoreApplication.translate("dlgPalletAddr", u"Dialog", None))
        self.groupBox.setTitle(QCoreApplication.translate("dlgPalletAddr", u"Ship From Address", None))
        self.label.setText(QCoreApplication.translate("dlgPalletAddr", u"Address 1 :", None))
        self.label_2.setText(QCoreApplication.translate("dlgPalletAddr", u"Address 2 :", None))
        self.label_3.setText(QCoreApplication.translate("dlgPalletAddr", u"Address 3 :", None))
        self.btn_FromPreview.setText(QCoreApplication.translate("dlgPalletAddr", u"PreVeiw", None))
        self.btn_FromSave.setText(QCoreApplication.translate("dlgPalletAddr", u"SAVE", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("dlgPalletAddr", u"Ship To Address", None))
        self.label_6.setText(QCoreApplication.translate("dlgPalletAddr", u"Address 1 :", None))
        self.label_4.setText(QCoreApplication.translate("dlgPalletAddr", u"Address 3 :", None))
        self.label_5.setText(QCoreApplication.translate("dlgPalletAddr", u"Address 2 :", None))
        self.btn_ToSave.setText(QCoreApplication.translate("dlgPalletAddr", u"SAVE", None))
        self.btn_ToPreview.setText(QCoreApplication.translate("dlgPalletAddr", u"PreVeiw", None))
        self.combo_ModelList.setItemText(0, QCoreApplication.translate("dlgPalletAddr", u"Select Model", None))

        self.label_7.setText(QCoreApplication.translate("dlgPalletAddr", u"MODEL  ::", None))
    # retranslateUi

