# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PalletLableUI.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QGroupBox,
    QHeaderView, QLCDNumber, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(876, 859)
        icon = QIcon()
        icon.addFile(u"C:/Users/user/Pictures/pallet.png", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(28, 32, 91, 21))
        font = QFont()
        font.setFamilies([u"Arial Black"])
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.edit_ChoicedModel = QLineEdit(Dialog)
        self.edit_ChoicedModel.setObjectName(u"edit_ChoicedModel")
        self.edit_ChoicedModel.setGeometry(QRect(488, 21, 351, 51))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(24)
        font1.setBold(True)
        self.edit_ChoicedModel.setFont(font1)
        self.edit_ChoicedModel.setAlignment(Qt.AlignCenter)
        self.edit_ChoicedModel.setReadOnly(True)
        self.combo_ModelList = QComboBox(Dialog)
        self.combo_ModelList.addItem("")
        self.combo_ModelList.setObjectName(u"combo_ModelList")
        self.combo_ModelList.setGeometry(QRect(120, 30, 271, 31))
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 180, 841, 81))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        self.groupBox_2.setFont(font2)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(90, 30, 101, 31))
        font3 = QFont()
        font3.setFamilies([u"\ud5e4\ub4dc\ub77c\uc778"])
        font3.setPointSize(20)
        font3.setBold(False)
        font3.setUnderline(True)
        self.label_4.setFont(font3)
        self.lcd_TodayCarton = QLCDNumber(self.groupBox_2)
        self.lcd_TodayCarton.setObjectName(u"lcd_TodayCarton")
        self.lcd_TodayCarton.setGeometry(QRect(400, 30, 101, 31))
        self.lcd_TodayPallet = QLCDNumber(self.groupBox_2)
        self.lcd_TodayPallet.setObjectName(u"lcd_TodayPallet")
        self.lcd_TodayPallet.setGeometry(QRect(690, 30, 101, 31))
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(260, 30, 131, 31))
        font4 = QFont()
        font4.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font4.setPointSize(15)
        font4.setBold(True)
        self.label_8.setFont(font4)
        self.label_8.setStyleSheet(u"background-color:rgb(238, 255, 222);\n"
"color:black;")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(550, 30, 131, 31))
        self.label_9.setFont(font4)
        self.label_9.setStyleSheet(u"background-color:rgb(238, 255, 222);\n"
"color:black;")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 80, 821, 81))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(90, 30, 201, 31))
        font5 = QFont()
        font5.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font5.setPointSize(23)
        font5.setBold(True)
        self.label_11.setFont(font5)
        self.edit_CartonID = QLineEdit(self.groupBox)
        self.edit_CartonID.setObjectName(u"edit_CartonID")
        self.edit_CartonID.setGeometry(QRect(310, 20, 391, 51))
        font6 = QFont()
        font6.setPointSize(23)
        self.edit_CartonID.setFont(font6)
        self.edit_CartonID.setAlignment(Qt.AlignCenter)
        self.btn_PrdSearch = QPushButton(Dialog)
        self.btn_PrdSearch.setObjectName(u"btn_PrdSearch")
        self.btn_PrdSearch.setGeometry(QRect(450, 280, 111, 41))
        font7 = QFont()
        font7.setBold(True)
        self.btn_PrdSearch.setFont(font7)
        self.btn_PrdSearch.setAutoDefault(False)
        self.btn_Reprint = QPushButton(Dialog)
        self.btn_Reprint.setObjectName(u"btn_Reprint")
        self.btn_Reprint.setGeometry(QRect(600, 280, 111, 41))
        font8 = QFont()
        font8.setPointSize(10)
        font8.setBold(True)
        self.btn_Reprint.setFont(font8)
        self.btn_Reprint.setAutoDefault(False)
        self.btn_DataClear = QPushButton(Dialog)
        self.btn_DataClear.setObjectName(u"btn_DataClear")
        self.btn_DataClear.setGeometry(QRect(300, 280, 111, 41))
        self.btn_DataClear.setFont(font7)
        self.btn_DataClear.setAutoDefault(False)
        self.tableWidget = QTableWidget(Dialog)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(20, 330, 831, 511))
        self.tableWidget.setFocusPolicy(Qt.WheelFocus)
        self.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(True)
        self.edit_Grid_Cnt = QLineEdit(Dialog)
        self.edit_Grid_Cnt.setObjectName(u"edit_Grid_Cnt")
        self.edit_Grid_Cnt.setEnabled(True)
        self.edit_Grid_Cnt.setGeometry(QRect(80, 290, 61, 31))
        font9 = QFont()
        font9.setPointSize(12)
        font9.setBold(True)
        self.edit_Grid_Cnt.setFont(font9)
        self.edit_Grid_Cnt.setAlignment(Qt.AlignCenter)
        self.edit_Grid_Cnt.setReadOnly(True)
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(18, 299, 56, 12))
        font10 = QFont()
        font10.setPointSize(11)
        font10.setBold(True)
        self.label_10.setFont(font10)
        self.btn_PrintNow = QPushButton(Dialog)
        self.btn_PrintNow.setObjectName(u"btn_PrintNow")
        self.btn_PrintNow.setGeometry(QRect(740, 280, 111, 41))
        self.btn_PrintNow.setFont(font8)
        self.btn_PrintNow.setAutoDefault(False)
        self.btn_AddressAdd = QPushButton(Dialog)
        self.btn_AddressAdd.setObjectName(u"btn_AddressAdd")
        self.btn_AddressAdd.setGeometry(QRect(160, 280, 111, 41))
        self.btn_AddressAdd.setFont(font7)
        self.btn_AddressAdd.setAutoDefault(False)
        QWidget.setTabOrder(self.edit_CartonID, self.btn_PrintNow)
        QWidget.setTabOrder(self.btn_PrintNow, self.combo_ModelList)
        QWidget.setTabOrder(self.combo_ModelList, self.edit_ChoicedModel)
        QWidget.setTabOrder(self.edit_ChoicedModel, self.tableWidget)
        QWidget.setTabOrder(self.tableWidget, self.btn_Reprint)
        QWidget.setTabOrder(self.btn_Reprint, self.btn_PrdSearch)
        QWidget.setTabOrder(self.btn_PrdSearch, self.btn_DataClear)
        QWidget.setTabOrder(self.btn_DataClear, self.edit_Grid_Cnt)

        self.retranslateUi(Dialog)
        self.btn_DataClear.clicked.connect(Dialog.btnDataClearClicked)
        self.btn_PrdSearch.clicked.connect(Dialog.btnDataSearchClicked)
        self.btn_Reprint.clicked.connect(Dialog.btnRePrintClicked)
        self.btn_PrintNow.clicked.connect(Dialog.btnPrintNowClicked)
        self.combo_ModelList.currentIndexChanged.connect(Dialog.comboModelChanged)
        self.edit_CartonID.returnPressed.connect(Dialog.InputCartonCheck)
        self.btn_AddressAdd.clicked.connect(Dialog.btnAddressAddClicked)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"MODEL  ::", None))
        self.combo_ModelList.setItemText(0, QCoreApplication.translate("Dialog", u"Select Model", None))

        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Quantity", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"TODAY", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"CARTON", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"PALLET", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Compare", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"CARTON ID :", None))
        self.btn_PrdSearch.setText(QCoreApplication.translate("Dialog", u"Data Search", None))
        self.btn_Reprint.setText(QCoreApplication.translate("Dialog", u"Re-Print", None))
        self.btn_DataClear.setText(QCoreApplication.translate("Dialog", u"Data Clear", None))
        self.edit_Grid_Cnt.setInputMask("")
        self.edit_Grid_Cnt.setPlaceholderText(QCoreApplication.translate("Dialog", u"0", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Count :: ", None))
        self.btn_PrintNow.setText(QCoreApplication.translate("Dialog", u"Print Now", None))
        self.btn_AddressAdd.setText(QCoreApplication.translate("Dialog", u"Address", None))
    # retranslateUi

